return {
  "vuki656/package-info.nvim",
  dependencies = "MunifTanjim/nui.nvim",
  ft = "json",
  opts = {
    autostart = true,
    hide_up_to_date = true,
    package_manager = "npm",
  },
  keys = {
    {
      "<leader>ns",
      '<cmd>lua require("package-info").show()<cr>',
      mode = { "n" },
      desc = "Show dependency versions",
      silent = true,
      noremap = true,
    },
    {
      "<leader>nh",
      '<cmd>lua require("package-info").hide()<cr>',
      mode = { "n" },
      desc = "Hide dependency versions",
      silent = true,
      noremap = true,
    },
    {
      "<leader>nt",
      '<cmd>lua require("package-info").toggle()<cr>',
      mode = { "n" },
      desc = "Toggle dependency versions",
      silent = true,
      noremap = true,
    },
    {
      "<leader>nu",
      '<cmd>lua require("package-info").update()<cr>',
      mode = { "n" },
      desc = "Update dependency on line",
      silent = true,
      noremap = true,
    },
    {
      "<leader>nd",
      '<cmd>lua require("package-info").delete()<cr>',
      mode = { "n" },
      desc = "Delete dependency on line",
      silent = true,
      noremap = true,
    },
    {
      "<leader>ni",
      '<cmd>lua require("package-info").install()<cr>',
      mode = { "n" },
      desc = "Install a new dependency",
      silent = true,
      noremap = true,
    },
    {
      "<leader>nc",
      '<cmd>lua require("package-info").change_version()<cr>',
      mode = { "n" },
      desc = "Install different dependency version",
      silent = true,
      noremap = true,
    },
  },
}