export PATH="$HOME/.local/bin:$PATH"

export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

# Added by LM Studio CLI (lms)
export PATH="$PATH:/Users/jasonsturges/.lmstudio/bin"
# End of LM Studio CLI section
